### ISSUE TITLE
Bind server to 0.0.0.0 rather than 127.0.0.1

### ISSUE THREAD

**Issue by karlwettin** [stts-se/symbolset#1]
https://github.com/stts-se/symbolset/blob/e0968a68ca017d386e77aff2af5e5e5c1f019a50/server/main.go#L213

Would it be possible to bind the server to all network devices rather than loopback?

**Comment by HannaLindgren** [comment]
> 
> 
> https://github.com/stts-se/symbolset/blob/e0968a68ca017d386e77aff2af5e5e5c1f019a50/server/main.go#L213
> 
> Would it be possible to bind the server to all network devices rather than loopback?

Did you try to set it to 0.0.0.0 using the host cmd line flag?
